---
- name: install python dev
  yum: name={{ item }} state=present
  with_items:
     - "{{ python_base_name }}-devel"
     - "{{ python_base_name }}-setuptools"
     - "{{ python_base_name }}-pip"
  tags:
    - python
    - packages

- name: install pillow
  yum: name={{ python_base_name }}-pillow state=present
  when: ansible_distribution_major_version|int > 6
  tags:
    - python
    - packages

- name: install PIL
  yum: name={{ python_base_name }}-imaging state=present
  when: ansible_distribution_major_version|int == 6
  tags:
    - python
    - packages

- name: install virtual env
  yum: name={{ item }} state=present
  with_items:
     - "{{ python_base_name }}-virtualenv"
     - "{{ python_base_name }}-virtualenv-clone"
     - "{{ python_base_name }}-virtualenvwrapper"
  tags:
    - python
    - packages

- name: install python drivers
  yum: name={{ item }} state=present
  with_items:
     - MySQL-python
     - python-memcached
  when: python_base_name == 'python'
  tags:
    - python
    - packages

- name: install mod_wsgi
  yum: name=mod_wsgi state=present
  when: python_base_name == 'python'
  tags:
    - python
    - packages

- name: configure main mod_wsgi settings
  template: src=wsgi.conf.j2  dest=/etc/httpd/conf.d/wsgi.conf mode=0644 owner=root group=root
  when: python_base_name == 'python'
  notify: restart httpd
  tags:
    - python
    - configuration
